"""Removed booking_time column

Revision ID: 57edfe238d8c
Revises: 
Create Date: 2024-11-14 09:45:28.222823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57edfe238d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_site_owner')
    with op.batch_alter_table('customer_bookings', schema=None) as batch_op:
        batch_op.drop_column('booking_time')

    with op.batch_alter_table('site_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('owner_password', sa.String(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'site_owner', ['site_owner_id'], ['site_owner_id'])
        batch_op.drop_column('owner_password')
        batch_op.drop_column('owner_name')

    with op.batch_alter_table('customer_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_time', sa.DATETIME(), nullable=False))

    op.create_table('_alembic_tmp_site_owner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['site_owner_id'], ['site_owner.id'], name='fk_site_owner_user'),
    sa.ForeignKeyConstraint(['site_owner_id'], ['site_owner.site_owner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
